[package]
name = "ultimate-neoplayer"
version = "0.1.0"
authors = ["arrudagates <arrudagates@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
rspotify = "0.10.0"
termion = "1.5.6"
tokio = { version = "0.2", features = ["full"] }
tui = "0.15.0"
unicode-width = "0.1.8"
